name: DCPrison
main: dk.doggycraft.dcprison.Prison
author: DoggyCraft
version: ${project.version}
api-version: 1.13
load: POSTWORLD
description: Essentials for DoggyCraft Prison
softdepend: [Vault, WorldGuard]
website: https://github.com/DoggyCraftDK/DCPrison
commands:
  prison:
    description: Controls the DCPrison system
    usage: /prison
permissions:
    prison.*:
        description: Gives the Player access to control the DCPrison system
        default: false
        children:
            prison.placesign: true
            prison.reload: true
            prison.showkill: false
            prison.irondoor: true
    prison.reload:
        description: Allows the Player to reload the DCPrison system
        default: false
    prison.placesign:
        description: Allows the Player to place Rankup and Prestige signs
        default: false
    prison.showkill:
        description: If the Player kills someone a custom kill message will be shown
        default: false
    prison.irondoor:
      description: Allows the Player to open iron doors in regions they are members of
      default: false